version: '3.8'

services:
  nestjs:
    container_name: nestjs
    build:
      context: ../
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ../.env
    ports:
      - '3001:3001'
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 30s
      timeout: 10s
      retries: 3
